### ISSUE TITLE
android.gradle_dependencies causes an error on Android

### ISSUE THREAD

**Issue by ToshiEAB** [teticio/kivy-tensorflow-helloworld#1]
Hello,

First of all, thanks for posting the kivy-tensorflow-helloworld program on Github. This was one of few sources I found relevant to my project. I'm trying to build an Android app with Tensorflow Lite and Kivy using Buildozer. I followed the instructions at https://github.com/teticio/kivy-tensorflow-helloworld but the app crashes every time I add "android.gradle_dependencies = "org.tensorflow:tensorflow-lite:+","org.tensorflow:tensorflow-lite-support:0.0.0-nightly"" to the buildozer.spec file. For this reason, I cannot use "Interpreter = autoclass('org.tensorflow.lite.Interpreter')" and other tensorlow.lite related codes in model.py. 

Will you please help me figure out why the app crashes?

Thanks in advance.

**Comment by hussam132** [comment]
you should debug your app to get the log that specify the error use `adb`

**Comment by DomagojHack** [comment]
Hi, I am trying to do the same and also encountered this problem. I see that you closed the issue as resolved. Can you please provide the details to figure out this issue?

**Comment by WikiGenius** [comment]
Hi @DomagojHack 

This is because the bulldozer version now is 1.5
change this line
android.gradle_dependencies = "org.tensorflow:tensorflow-lite:+","org.tensorflow:tensorflow-lite-support:+"
to 
android.gradle_dependencies = org.tensorflow:tensorflow-lite:+,org.tensorflow:tensorflow-lite-support:+

**Comment by teticio** [comment]
Thanks for this @WikiGenius ! I have pushed this change.
