### ISSUE TITLE
Could not find "org.tensorflow:tensorflow-lite:+"

### ISSUE THREAD

**Issue by WikiGenius** [teticio/kivy-tensorflow-helloworld#2]
Hello
When I ran the code 

I got this error  in the files
* What went wrong:
Execution failed for task ':checkDebugAarMetadata'.
> Could not resolve all files for configuration ':debugRuntimeClasspath'.
   > Could not find "org.tensorflow:tensorflow-lite:+".
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/"org/tensorflow/tensorflow-lite/+"/tensorflow-lite-+".pom
       - https://jcenter.bintray.com/"org/tensorflow/tensorflow-lite/+"/tensorflow-lite-+".pom
       - file:/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/kivy-tensorflow-helloworld/.buildozer/android/platform/build-arm64-v8a/dists/myapp/libs/tensorflow-lite-+".jar
       - file:/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/kivy-tensorflow-helloworld/.buildozer/android/platform/build-arm64-v8a/dists/myapp/libs/tensorflow-lite.jar
     Required by:
         project :
   > Could not find "org.tensorflow:tensorflow-lite-support:+".
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/"org/tensorflow/tensorflow-lite-support/+"/tensorflow-lite-support-+".pom
       - https://jcenter.bintray.com/"org/tensorflow/tensorflow-lite-support/+"/tensorflow-lite-support-+".pom
       - file:/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/kivy-tensorflow-helloworld/.buildozer/android/platform/build-arm64-v8a/dists/myapp/libs/tensorflow-lite-support-+".jar
       - file:/home/muhammed/Main/programming/upwork/clients/Ritesh-Kanjee-YOLO/kivy-tensorflow-helloworld/.buildozer/android/platform/build-arm64-v8a/dists/myapp/libs/tensorflow-lite-support.jar
     Required by:
         project :

**Comment by WikiGenius** [comment]
I solved the problem
I think it is because the bulldozer version now is 1.5
change this line
android.gradle_dependencies = "org.tensorflow:tensorflow-lite:+","org.tensorflow:tensorflow-lite-support:+"
to 
android.gradle_dependencies = org.tensorflow:tensorflow-lite:+,org.tensorflow:tensorflow-lite-support:+

**Comment by teticio** [comment]
Thanks again!

**Comment by WikiGenius** [comment]
you are welcome @teticio
